-- Copies MicrobiomeRX's schema into CLP Compass's Supabase project, namespaced
-- with an mrx_ prefix so nothing collides with CLP Compass's own tables (it
-- has its own unrelated `patients` table, for instance). This is a straight
-- schema mirror of MicrobiomeRX's live database (read via its PostgREST
-- OpenAPI spec) — column names/types/defaults match the source as closely as
-- could be determined; only foreign keys the source's own API explicitly
-- reported are recreated here, nothing invented.
--
-- Run this once, manually, in the Supabase SQL editor for this project
-- (jtidesyasvaiztbxkcgz, cliniclivingplus) — same as every other migration
-- in this repo, none of which are auto-applied.
--
-- After this runs, a separate script copies the actual row data + the
-- original PDF files from MicrobiomeRX's Storage bucket into these tables
-- and the mrx-reports bucket created below.

create extension if not exists vector;

-- Reference/lookup tables (no dependencies) --------------------------------

create table if not exists mrx_doctors (
  id uuid primary key default gen_random_uuid(),
  email text,
  full_name text,
  clinic_name text,
  signature_data_url text,
  degree text default 'MBBS',
  reg_no text,
  name text,
  user_id uuid,
  created_at timestamptz default now()
);

create table if not exists mrx_aic_product_categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  created_at timestamptz default now()
);

create table if not exists mrx_aic_peptides (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  form_factor text,
  quantity text,
  brand text,
  notes text,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists mrx_species_profiles (
  id uuid primary key default gen_random_uuid(),
  species_name text not null,
  genus text,
  role text,
  low_levels_associated_with text[],
  high_levels_associated_with text[],
  clinical_action text,
  metabolic_functions text[],
  produces text[],
  pathogenic boolean default false,
  source text default 'groq-llama-70b',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists mrx_contraindications (
  id uuid primary key default gen_random_uuid(),
  supplement text not null,
  condition text not null,
  reason text,
  severity text default 'caution',
  created_at timestamptz default now()
);

create table if not exists mrx_marker_dictionary (
  id integer generated by default as identity primary key,
  rowid integer,
  markername text not null,
  bugspeaks_category text,
  report_section text,
  bin_system text,
  status_values text,
  optimal_state text,
  what_low_means_clinically text,
  what_high_means_clinically text,
  key_cofactor_markers text,
  software_lookup_key text,
  created_at timestamptz default now()
);

create table if not exists mrx_reference_ranges (
  id uuid primary key default gen_random_uuid(),
  metric text not null,
  category text not null,
  low numeric not null,
  high numeric not null,
  report_type text default 'bugspeaks',
  version text default 'v1',
  unit text,
  pmids text[],
  created_at timestamptz default now()
);

create table if not exists mrx_rules_versions (
  id uuid primary key default gen_random_uuid(),
  version text not null,
  description text,
  created_at timestamptz default now()
);

create table if not exists mrx_probiotic_matrix (
  id integer generated by default as identity primary key,
  rowid integer,
  probiotic_name text not null,
  strain_code text,
  probiotic_category text,
  cfu_range text,
  health_function text,
  bugspeaks_when_low text,
  key_mechanism text,
  contraindications text,
  protocol_phase text,
  stacks_with text,
  notes text,
  created_at timestamptz default now()
);

create table if not exists mrx_dietary_protocols (
  id integer generated by default as identity primary key,
  rowid integer,
  condition_name text not null,
  phase text,
  duration text,
  foods_include text,
  foods_exclude text,
  fermented_foods text,
  prebiotic_foods text,
  fibre_target text,
  hydration_target text,
  specific_instructions text,
  dietary_framework text,
  bugspeaks_phase_mapping text,
  created_at timestamptz default now()
);

create table if not exists mrx_therapy_protocols (
  id integer generated by default as identity primary key,
  rowid integer,
  condition_name text not null,
  therapy_type text,
  modality text,
  tier_indication text,
  rych_index_range text,
  frequency text,
  dosing_protocol text,
  course_length text,
  contraindication_screen text,
  stacks_with text,
  research_reference text,
  notes text,
  created_at timestamptz default now()
);

create table if not exists mrx_marker_protocol_map (
  id integer generated by default as identity primary key,
  rowid integer,
  bugspeaks_section text,
  markername text not null,
  status text not null,
  threshold_note text,
  condition_flagged text,
  severity text,
  priority_score integer,
  "5r_step" text,
  protocol_phase text,
  phase_1_action text,
  phase_2_action text,
  phase_3_action text,
  clinical_reasoning text,
  research_evidence text,
  contraindication_flags text,
  created_at timestamptz default now()
);

create table if not exists mrx_supplement_stack (
  id integer generated by default as identity primary key,
  rowid integer,
  condition_name text not null,
  supplement_priority integer,
  product_name text not null,
  aic_product_name text,
  aic_match_notes text,
  aic_category text,
  dose text,
  timing text,
  duration text,
  mechanism text,
  protocol_phase text,
  notes text,
  created_at timestamptz default now()
);

create table if not exists mrx_knowledge_chunks (
  id uuid primary key default gen_random_uuid(),
  source_file text,
  chunk_index integer,
  content text,
  embedding vector(384),
  created_at timestamptz default now()
);

-- aic_products is an FK target (product_key) for several tables below, so
-- product_key needs its own uniqueness constraint alongside the id PK.
create table if not exists mrx_aic_products (
  id uuid primary key default gen_random_uuid(),
  product_key text not null unique,
  name text not null,
  subtitle text,
  dose text,
  timing text,
  phase integer not null,
  category text not null,
  ingredients jsonb,
  note text,
  rotation jsonb,
  active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists mrx_aic_ingredients_full (
  id uuid primary key default gen_random_uuid(),
  product_key text references mrx_aic_products(product_key),
  ingredient text,
  amount text,
  unit text,
  rda_pct text,
  is_proprietary boolean,
  blend_name text,
  sort_order integer,
  product_name text,
  category text,
  phase integer,
  created_at timestamptz default now()
);

create table if not exists mrx_aic_product_ingredients (
  id uuid primary key default gen_random_uuid(),
  product_key text not null references mrx_aic_products(product_key),
  ingredient text not null,
  amount text,
  unit text,
  rda_pct text,
  is_proprietary boolean default false,
  blend_name text,
  sort_order integer default 0,
  created_at timestamptz default now()
);

create table if not exists mrx_aic_supplement_protocols (
  id uuid primary key default gen_random_uuid(),
  condition text not null,
  duration text,
  disclaimer text default 'For educative purpose only. Please consult your doctor for treatment and protocols.',
  notes text,
  created_at timestamptz default now()
);

create table if not exists mrx_aic_protocol_steps (
  id uuid primary key default gen_random_uuid(),
  protocol_id uuid not null references mrx_aic_supplement_protocols(id),
  time_of_day text,
  sort_order integer default 0,
  product_name text not null,
  product_key text references mrx_aic_products(product_key),
  dose_note text,
  month_note text,
  created_at timestamptz default now()
);

create table if not exists mrx_aic_protocol_steps_full (
  id uuid primary key default gen_random_uuid(),
  protocol_id uuid references mrx_aic_supplement_protocols(id),
  time_of_day text,
  sort_order integer,
  product_name text,
  product_key text references mrx_aic_products(product_key),
  dose_note text,
  month_note text,
  condition text,
  duration text,
  disclaimer text,
  created_at timestamptz
);

-- Patient-facing tables ------------------------------------------------------

create table if not exists mrx_patients (
  id uuid primary key default gen_random_uuid(),
  doctor_id uuid,
  name text not null,
  age_sex text,
  complaint text,
  diet_type text,
  medical_history text,
  allergies text,
  created_at timestamptz default now()
);

create table if not exists mrx_reports (
  id uuid primary key default gen_random_uuid(),
  doctor_id uuid,
  patient_id uuid references mrx_patients(id),
  patient_name text not null,
  patient_age_sex text,
  patient_diet text,
  patient_history text,
  patient_allergies text,
  pdf_filename text,
  species_list text[] not null default '{}',
  species_count integer,
  report_data jsonb,
  rules_output jsonb,
  rules_version text default 'v1.0.0',
  recommendations jsonb,
  nutrition_plan jsonb,
  section_analyses jsonb,
  pdf_text text,
  sample_date text,
  aic_supplement_recommendations jsonb,
  aic_rules_version text,
  created_at timestamptz default now()
);

create table if not exists mrx_report_summaries (
  id uuid primary key default gen_random_uuid(),
  report_id uuid references mrx_reports(id),
  summary_text text,
  gut_score integer,
  key_findings jsonb,
  red_flags jsonb,
  created_at timestamptz default now()
);

create table if not exists mrx_prescriptions (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid references mrx_patients(id),
  doctor_id uuid,
  report_id uuid references mrx_reports(id),
  rx_data jsonb not null,
  created_at timestamptz default now(),
  approved_at timestamptz,
  approved_by uuid
);

create table if not exists mrx_doctor_feedback (
  id uuid primary key default gen_random_uuid(),
  doctor_id uuid,
  category text default 'suggestion',
  message text not null,
  status text default 'unread',
  created_at timestamptz default now()
);

-- Linking table for a future screen where a coach manually connects a
-- MicrobiomeRX patient record to the matching CLP Compass patient record.
-- Empty for now — MicrobiomeRX has no shared identifier (email/phone/clinic
-- id) with CLP Compass's patients today, so this can't be populated
-- automatically.
create table if not exists mrx_patient_links (
  id uuid primary key default gen_random_uuid(),
  clp_patient_id uuid not null references patients(id) on delete cascade,
  mrx_patient_id uuid not null references mrx_patients(id) on delete cascade,
  linked_at timestamptz default now(),
  linked_by text,
  unique (clp_patient_id, mrx_patient_id)
);

-- Storage bucket for the copied original PDF files (mirrors MicrobiomeRX's
-- own supabase/storage-setup.sql bucket definition).
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'mrx-reports',
  'mrx-reports',
  false,
  52428800,
  array['application/pdf']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
